server:
  port: ${PORT:8090}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://${DB_HOST}/~/test2;SCHEMA=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}