CREATE TABLE USER_CREDENTIAL(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NAME VARCHAR(100) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  DATE_OF_BIRTH DATE NOT NULL
  );

CREATE TABLE STUDENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE TEACHER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE PARENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE DIRECTOR(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE LESSON(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   LESSON_NAME VARCHAR(100) NOT NULL,
   DATE_OF_LESSON DATE NOT NULL,
   TEACHER_ID BIGINT NOT NULL UNIQUE,
   FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (ID)
   );

CREATE TABLE HOMEWORK(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   HOMEWORK_DESCRIPTION VARCHAR(100) NOT NULL,
   LESSON_ID BIGINT NOT NULL UNIQUE,
   FOREIGN KEY (LESSON_ID) REFERENCES LESSON (ID)
   );

CREATE TABLE LESSON_STUDENT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LESSON_ID BIGINT NOT NULL,
    STUDENT_ID BIGINT NOT NULL,
    FOREIGN KEY (LESSON_ID) REFERENCES LESSON (ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
   );