CREATE TABLE USER_CREDENTIAL(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NAME VARCHAR(100) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  DATE_OF_BIRTH DATE NOT NULL
  );

CREATE TABLE STUDENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE TEACHER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE PARENT(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );

CREATE TABLE DIRECTOR(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CREDENTIAL_ID BIGINT,
  FOREIGN KEY (CREDENTIAL_ID) REFERENCES USER_CREDENTIAL (ID)
  );